//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 29 12:13:33 CEST 2010
//----------------------------------------------------

package be.ac.info.fundp.TVLParser.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */
	public static final int TIMES = 43;
	public static final int BOOL = 10;
	public static final int XORAGG = 53;
	public static final int REAL = 4;
	public static final int CBRA = 64;
	public static final int CHILDREN = 24;
	public static final int GROUP = 18;
	public static final int PARENT = 22;
	public static final int CONST = 17;
	public static final int EXCLUDES = 57;
	public static final int OPT = 8;
	public static final int GEQ = 38;
	public static final int ENUM = 12;
	public static final int ALLOF = 21;
	public static final int IFANDONLYIF = 30;
	public static final int COMMA = 61;
	public static final int SUM = 47;
	public static final int INTEGER = 3;
	public static final int STRUCT = 13;
	public static final int REQUIRES = 58;
	public static final int BRA = 62;
	public static final int FALSE = 33;
	public static final int NOT = 31;
	public static final int ORAGG = 52;
	public static final int NOTEQUALS = 34;
	public static final int MIN = 46;
	public static final int ANDAGG = 51;
	public static final int IFOUT = 16;
	public static final int LOWER = 37;
	public static final int MUL = 48;
	public static final int ROOT = 7;
	public static final int BRAEND = 63;
	public static final int CBRAEND = 65;
	public static final int IFIN = 15;
	public static final int TRUE = 32;
	public static final int ZERO = 2;
	public static final int PLUS = 40;
	public static final int DIVIDE = 44;
	public static final int REALP = 14;
	public static final int GREATER = 36;
	public static final int MAX = 45;
	public static final int INVERSEIMPLIES = 28;
	public static final int DOT = 66;
	public static final int INT = 11;
	public static final int AVG = 49;
	public static final int EOF = 0;
	public static final int SEMICOLON = 69;
	public static final int THIS = 23;
	public static final int COUNT = 50;
	public static final int SQBRAEND = 60;
	public static final int SOMEOF = 20;
	public static final int IS = 56;
	public static final int MINUS = 41;
	public static final int IN = 55;
	public static final int OR = 27;
	public static final int error = 1;
	public static final int SQBRA = 59;
	public static final int DATA = 70;
	public static final int ID = 71;
	public static final int ONEOF = 19;
	public static final int ABS = 54;
	public static final int COLON = 68;
	public static final int MANY = 9;
	public static final int QUEST = 67;
	public static final int STRING = 5;
	public static final int SHARED = 6;
	public static final int AND = 26;
	public static final int IMPLIES = 29;
	public static final int UMINUS = 42;
	public static final int SCHILDREN = 25;
	public static final int EQUALS = 35;
	public static final int LEQ = 39;
}
